### ISSUE TITLE
Variable substitution issues

### ISSUE THREAD

**Issue by w0** [CharlesNRU/mdm-adminservice#2]
Running into an issue with the Invoke-GetPackageIDFromAdminService step. Basically everything after the -Password parameter is not getting its variable substituted with the value. 

```
-ServerFQDN 'myserver.local' -UserName 'myuser@ad.local' -Password 'ItsaPassw0rd' -BypassCertCheck %BypassCertCheck%
```

**Comment by CharlesNRU** [comment]
I'm going to need more information than that to help you out. Have you tried using the TS debugger to see if the TS variables are populated in the task sequence at this step?

**Comment by w0** [comment]
Yea, when I use the TS debugger, I can see all the values are populated and not null. If I open up a powershell window and try and access the values, I am to get the correct data from them. 

Below is the PowerShell parameters from my smsts.log. I changed the parameter for BypassCert check from the variable to true. But the issue just pops up further down the parameter list anyways
```
CommandLine: '"X:\windows\system32\windowspowershell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& 'X:\windows\TEMP\SMSTSPowerShellScripts\{DCCA075F-A887-4C7A-B1B8-AB134089A05B}.PS1' -ServerFQDN 'myserver.local' -Username 'myacct@local.local' -Password 'MyPass' -BypassCertCheck $true -Manufacturer '%DATManufacturer%' -Model '%DATModel%' -SystemSKU '%DATSystemSKU%' -PackageType '%PackageType%' -PilotPackages %PilotPackages% -DriverPackageOSArch '%DriverPackageOSArch%' -DriverPackageReleaseId %DriverPackageReleaseId% -CurrentBIOSVersion '%DATCurrentBIOSVersion%' -CurrentBIOSReleaseDate '%DATCurrentBIOSReleaseDate%' -LogPath %_SMSTSLogPath% ; exit ($LASTEXITCODE -bor [int](-not $? -and -not $LASTEXITCODE)) "'
```

I am on version 2111

**Comment by CharlesNRU** [comment]
Hmm OK, and did it ever work for you before or you are trying to get this working for the first time?
Did it start not working after a recent upgrade?
Sorry I don't have access to my ConfigMgr environment at the moment to do testing on my side...
Could you try changing the single quotes to double quotes in the task sequence step to see if that works?

**Comment by w0** [comment]
Trying to get it working for the first time. Tried changing to double quotes and the same issue persists. Starting to wonder if there is some configmgr setting box I need to tick or something

**Comment by CharlesNRU** [comment]
This is weird... Can you try re-creating the run powershell command step? I wonder if something changed in the step in a newer release.

**Comment by w0** [comment]
I think I figured it out. My password had an '&' in it. My best guess was that was being treated as an execution or something. Once I changed the password to something else, all the variables are now being substituted as expected.
