### ISSUE TITLE
The remote server returned an error (400) Bad request. Error in line 473. The line 473...

### ISSUE THREAD

**Issue by bohnanza22** [CharlesNRU/mdm-adminservice#3]
Thankyou for this MDM solution I really like the way it is implemented.  Unfortunately I have ran into an issue that I haven't found a solution for. We upgraded our CM environment to 2211 and we are now getting this issue.

the remote server returned an error (400) Bad request. Error in line 473. The line 473 contains the following:

$Packages = Invoke-RestMethod -Method Get -Uri $WMIPackageURL -Body $Body @InvokeRestMethodCredential | Select-Object -ExpandProperty value

[GetPackageID_DriverPackage.log](https://github.com/CharlesNRU/mdm-adminservice/files/10573890/GetPackageID_DriverPackage.log)
[GetPackageID_BIOSPackage.log](https://github.com/CharlesNRU/mdm-adminservice/files/10573891/GetPackageID_BIOSPackage.log)

Thankyou for any help you can provide.

**Comment by CharlesNRU** [comment]
Hello there,

I have just pushed an update to the script in the repository. I believe it should fix the issue. You should be able to copy-paste the script in the task sequence. I have not updated the MDM-TS.zip file because i don't have access to a lab environment where I can export the updated TS right now.

Can you let me know if it works or not?

**Comment by bohnanza22** [comment]
Hi, Thanks for the quick response!  I have tested it in my OSD and a TS deployed via Software Center in Full OS.  I am now getting these errors: 

`Error: -2146233087): The property 'Query' cannot be found on this object. Verify that the property exists and can be set.`

```
At C:\WINDOWS\TEMP\SMSTSPowerShellScripts\{A7FB4E8D-1861-4384-A782-603437951016}.PS1:480 char:9
+         $Request.Query = $BodyParameters.ToString()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I am attaching scrubbed versions of my logs as well.  

[GetPackageID_BIOSPackage.log](https://github.com/CharlesNRU/mdm-adminservice/files/10667803/GetPackageID_BIOSPackage.log)
[GetPackageID_DriverPackage.log](https://github.com/CharlesNRU/mdm-adminservice/files/10667805/GetPackageID_DriverPackage.log)

**Comment by bohnanza22** [comment]
I think narrowed down the issue.  There is a typo on line 448 and 449, `$WMIPackageURL` should be `$WMIPackageURI` matching the same variable on line 479. Once I made the change it seems to be working. I will be doing more testing tomorrow.

**Comment by CharlesNRU** [comment]
I believe you are right, I made a typo. I just updated the script on the repository.
Thank you for your help troubleshooting this issue.

**Comment by bohnanza22** [comment]
The script update is working in my environment now.  Thanks again for your help.
