### ISSUE TITLE
Packaging Invoke-GetPackageIDFromAdminService.ps1

### ISSUE THREAD

**Issue by ehousse** [CharlesNRU/mdm-adminservice#4]
The Invoke-GetPackageIDFromAdminService.ps1 script seem to fail when I put it inside a packages, run perfectly fine when placed directly in the TS.  Are the variables passed correctly when the script is being pulled from a package?

**Comment by CharlesNRU** [comment]
Hello, do you have any more information you can share? Does the script get executed at all? Is there a sanitized log file you could share?
